package poly.app.core.entities;
// Generated Nov 2, 2018 5:32:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DoAnChiTiet generated by hbm2java
 */
public class DoAnChiTiet  implements java.io.Serializable {


     private Integer id;
     private DoAn doAn;
     private KichCoDoAn kichCoDoAn;
     private int donGia;
     private Set<HoaDonChiTiet> hoaDonChiTiets = new HashSet<HoaDonChiTiet>(0);

    public DoAnChiTiet() {
    }

	
    public DoAnChiTiet(DoAn doAn, KichCoDoAn kichCoDoAn, int donGia) {
        this.doAn = doAn;
        this.kichCoDoAn = kichCoDoAn;
        this.donGia = donGia;
    }
    public DoAnChiTiet(DoAn doAn, KichCoDoAn kichCoDoAn, int donGia, Set<HoaDonChiTiet> hoaDonChiTiets) {
       this.doAn = doAn;
       this.kichCoDoAn = kichCoDoAn;
       this.donGia = donGia;
       this.hoaDonChiTiets = hoaDonChiTiets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DoAn getDoAn() {
        return this.doAn;
    }
    
    public void setDoAn(DoAn doAn) {
        this.doAn = doAn;
    }
    public KichCoDoAn getKichCoDoAn() {
        return this.kichCoDoAn;
    }
    
    public void setKichCoDoAn(KichCoDoAn kichCoDoAn) {
        this.kichCoDoAn = kichCoDoAn;
    }
    public int getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(int donGia) {
        this.donGia = donGia;
    }
    public Set<HoaDonChiTiet> getHoaDonChiTiets() {
        return this.hoaDonChiTiets;
    }
    
    public void setHoaDonChiTiets(Set<HoaDonChiTiet> hoaDonChiTiets) {
        this.hoaDonChiTiets = hoaDonChiTiets;
    }




}


