package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GheNgoi generated by hbm2java
 */
public class GheNgoi  implements java.io.Serializable {


     private Integer id;
     private LoaiGhe loaiGhe;
     private PhongChieu phongChieu;
     private String viTriDay;
     private int viTriCot;
     private Set<VeBan> veBans = new HashSet<VeBan>(0);

    public GheNgoi() {
    }

	
    public GheNgoi(LoaiGhe loaiGhe, PhongChieu phongChieu, String viTriDay, int viTriCot) {
        this.loaiGhe = loaiGhe;
        this.phongChieu = phongChieu;
        this.viTriDay = viTriDay;
        this.viTriCot = viTriCot;
    }
    public GheNgoi(LoaiGhe loaiGhe, PhongChieu phongChieu, String viTriDay, int viTriCot, Set<VeBan> veBans) {
       this.loaiGhe = loaiGhe;
       this.phongChieu = phongChieu;
       this.viTriDay = viTriDay;
       this.viTriCot = viTriCot;
       this.veBans = veBans;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LoaiGhe getLoaiGhe() {
        return this.loaiGhe;
    }
    
    public void setLoaiGhe(LoaiGhe loaiGhe) {
        this.loaiGhe = loaiGhe;
    }
    public PhongChieu getPhongChieu() {
        return this.phongChieu;
    }
    
    public void setPhongChieu(PhongChieu phongChieu) {
        this.phongChieu = phongChieu;
    }
    public String getViTriDay() {
        return this.viTriDay;
    }
    
    public void setViTriDay(String viTriDay) {
        this.viTriDay = viTriDay;
    }
    public int getViTriCot() {
        return this.viTriCot;
    }
    
    public void setViTriCot(int viTriCot) {
        this.viTriCot = viTriCot;
    }
    public Set<VeBan> getVeBans() {
        return this.veBans;
    }
    
    public void setVeBans(Set<VeBan> veBans) {
        this.veBans = veBans;
    }




}


