package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GiaVe generated by hbm2java
 */
public class GiaVe  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private int donGia;
     private Set<VeBan> veBans = new HashSet<VeBan>(0);

    public GiaVe() {
    }

	
    public GiaVe(String ten, int donGia) {
        this.ten = ten;
        this.donGia = donGia;
    }
    public GiaVe(String ten, int donGia, Set<VeBan> veBans) {
       this.ten = ten;
       this.donGia = donGia;
       this.veBans = veBans;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public int getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(int donGia) {
        this.donGia = donGia;
    }
    public Set<VeBan> getVeBans() {
        return this.veBans;
    }
    
    public void setVeBans(Set<VeBan> veBans) {
        this.veBans = veBans;
    }




}


