package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon  implements java.io.Serializable {


     private String id;
     private NguoiDung nguoiDung;
     private Date ngayBan;
     private Set<HoaDonChiTiet> hoaDonChiTiets = new HashSet<HoaDonChiTiet>(0);

    public HoaDon() {
    }

	
    public HoaDon(String id, NguoiDung nguoiDung, Date ngayBan) {
        this.id = id;
        this.nguoiDung = nguoiDung;
        this.ngayBan = ngayBan;
    }
    public HoaDon(String id, NguoiDung nguoiDung, Date ngayBan, Set<HoaDonChiTiet> hoaDonChiTiets) {
       this.id = id;
       this.nguoiDung = nguoiDung;
       this.ngayBan = ngayBan;
       this.hoaDonChiTiets = hoaDonChiTiets;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }
    public Date getNgayBan() {
        return this.ngayBan;
    }
    
    public void setNgayBan(Date ngayBan) {
        this.ngayBan = ngayBan;
    }
    public Set<HoaDonChiTiet> getHoaDonChiTiets() {
        return this.hoaDonChiTiets;
    }
    
    public void setHoaDonChiTiets(Set<HoaDonChiTiet> hoaDonChiTiets) {
        this.hoaDonChiTiets = hoaDonChiTiets;
    }




}


