package poly.app.core.entities;
// Generated Nov 2, 2018 5:32:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LoaiDoAn generated by hbm2java
 */
public class LoaiDoAn  implements java.io.Serializable {


     private int id;
     private String ten;
     private Set<DoAn> doAns = new HashSet<DoAn>(0);

    public LoaiDoAn() {
    }

	
    public LoaiDoAn(int id, String ten) {
        this.id = id;
        this.ten = ten;
    }
    public LoaiDoAn(int id, String ten, Set<DoAn> doAns) {
       this.id = id;
       this.ten = ten;
       this.doAns = doAns;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set<DoAn> getDoAns() {
        return this.doAns;
    }
    
    public void setDoAns(Set<DoAn> doAns) {
        this.doAns = doAns;
    }




}


