package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NguoiDung generated by hbm2java
 */
public class NguoiDung  implements java.io.Serializable {


     private String id;
     private VaiTro vaiTro;
     private String hoTen;
     private String matKhau;
     private String soCmnd;
     private String soDienThoai;
     private String email;
     private String diaChi;
     private Date ngayVaoLam;
     private boolean gioiTinh;
     private Set<VeBan> veBans = new HashSet<VeBan>(0);
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public NguoiDung() {
    }

	
    public NguoiDung(String id, VaiTro vaiTro, String hoTen, String matKhau, String soCmnd, String soDienThoai, Date ngayVaoLam, boolean gioiTinh) {
        this.id = id;
        this.vaiTro = vaiTro;
        this.hoTen = hoTen;
        this.matKhau = matKhau;
        this.soCmnd = soCmnd;
        this.soDienThoai = soDienThoai;
        this.ngayVaoLam = ngayVaoLam;
        this.gioiTinh = gioiTinh;
    }
    public NguoiDung(String id, VaiTro vaiTro, String hoTen, String matKhau, String soCmnd, String soDienThoai, String email, String diaChi, Date ngayVaoLam, boolean gioiTinh, Set<VeBan> veBans, Set<HoaDon> hoaDons) {
       this.id = id;
       this.vaiTro = vaiTro;
       this.hoTen = hoTen;
       this.matKhau = matKhau;
       this.soCmnd = soCmnd;
       this.soDienThoai = soDienThoai;
       this.email = email;
       this.diaChi = diaChi;
       this.ngayVaoLam = ngayVaoLam;
       this.gioiTinh = gioiTinh;
       this.veBans = veBans;
       this.hoaDons = hoaDons;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public VaiTro getVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(VaiTro vaiTro) {
        this.vaiTro = vaiTro;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getSoCmnd() {
        return this.soCmnd;
    }
    
    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Date getNgayVaoLam() {
        return this.ngayVaoLam;
    }
    
    public void setNgayVaoLam(Date ngayVaoLam) {
        this.ngayVaoLam = ngayVaoLam;
    }
    public boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Set<VeBan> getVeBans() {
        return this.veBans;
    }
    
    public void setVeBans(Set<VeBan> veBans) {
        this.veBans = veBans;
    }
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }


    public boolean isName(){
        return this.gioiTinh;
    }

}


