package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VaiTro generated by hbm2java
 */
public class VaiTro  implements java.io.Serializable {


     private String id;
     private String ten;
     private Set<NguoiDung> nguoiDungs = new HashSet<NguoiDung>(0);

    public VaiTro() {
    }

	
    public VaiTro(String id, String ten) {
        this.id = id;
        this.ten = ten;
    }
    public VaiTro(String id, String ten, Set<NguoiDung> nguoiDungs) {
       this.id = id;
       this.ten = ten;
       this.nguoiDungs = nguoiDungs;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Set<NguoiDung> getNguoiDungs() {
        return this.nguoiDungs;
    }
    
    public void setNguoiDungs(Set<NguoiDung> nguoiDungs) {
        this.nguoiDungs = nguoiDungs;
    }




}


