package poly.app.core.entities;
// Generated Nov 2, 2018 5:32:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VeDat generated by hbm2java
 */
public class VeDat  implements java.io.Serializable {


     private String id;
     private GheNgoi gheNgoi;
     private GiaVe giaVe;
     private KhachHang khachHang;
     private SuatChieu suatChieu;
     private Date ngayDat;
     private Integer tongCong;

    public VeDat() {
    }

	
    public VeDat(String id, GheNgoi gheNgoi, GiaVe giaVe, KhachHang khachHang, SuatChieu suatChieu, Date ngayDat) {
        this.id = id;
        this.gheNgoi = gheNgoi;
        this.giaVe = giaVe;
        this.khachHang = khachHang;
        this.suatChieu = suatChieu;
        this.ngayDat = ngayDat;
    }
    public VeDat(String id, GheNgoi gheNgoi, GiaVe giaVe, KhachHang khachHang, SuatChieu suatChieu, Date ngayDat, Integer tongCong) {
       this.id = id;
       this.gheNgoi = gheNgoi;
       this.giaVe = giaVe;
       this.khachHang = khachHang;
       this.suatChieu = suatChieu;
       this.ngayDat = ngayDat;
       this.tongCong = tongCong;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public GheNgoi getGheNgoi() {
        return this.gheNgoi;
    }
    
    public void setGheNgoi(GheNgoi gheNgoi) {
        this.gheNgoi = gheNgoi;
    }
    public GiaVe getGiaVe() {
        return this.giaVe;
    }
    
    public void setGiaVe(GiaVe giaVe) {
        this.giaVe = giaVe;
    }
    public KhachHang getKhachHang() {
        return this.khachHang;
    }
    
    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }
    public SuatChieu getSuatChieu() {
        return this.suatChieu;
    }
    
    public void setSuatChieu(SuatChieu suatChieu) {
        this.suatChieu = suatChieu;
    }
    public Date getNgayDat() {
        return this.ngayDat;
    }
    
    public void setNgayDat(Date ngayDat) {
        this.ngayDat = ngayDat;
    }
    public Integer getTongCong() {
        return this.tongCong;
    }
    
    public void setTongCong(Integer tongCong) {
        this.tongCong = tongCong;
    }




}


