package poly.app.core.entities;
// Generated Nov 3, 2018 9:52:40 PM by Hibernate Tools 4.3.1



/**
 * VeDat generated by hbm2java
 */
public class VeDat  implements java.io.Serializable {


     private String id;
     private KhachHang khachHang;
     private VeBan veBan;

    public VeDat() {
    }

    public VeDat(String id, KhachHang khachHang, VeBan veBan) {
       this.id = id;
       this.khachHang = khachHang;
       this.veBan = veBan;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public KhachHang getKhachHang() {
        return this.khachHang;
    }
    
    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }
    public VeBan getVeBan() {
        return this.veBan;
    }
    
    public void setVeBan(VeBan veBan) {
        this.veBan = veBan;
    }




}


